language: php

php: 
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev
  - mysql -e 'create database `database`;'
  - php artisan tyloo:app:setup

script: phpunit